### ISSUE TITLE
add support for Claude 3

### ISSUE THREAD

**Issue by snowolf** [aws-samples/amazon-bedrock-serverless-prompt-chaining#214]
Hi,

Is there any plan to add support Claude 3, thanks a lot!

**Comment by clareliguori** [comment]
Hello, I haven't tested it, but the example app should already support Claude 3. It already uses the new [Claude messages API](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages.html) required for Claude 3.

To update the model used by the demos in your fork, update the following lines:
* https://github.com/aws-samples/amazon-bedrock-serverless-prompt-chaining/blob/main/stacks/util.py#L45-L48
* https://github.com/aws-samples/amazon-bedrock-serverless-prompt-chaining/blob/main/stacks/util.py#L111
* https://github.com/aws-samples/amazon-bedrock-serverless-prompt-chaining/blob/main/stacks/util.py#L208
* https://github.com/aws-samples/amazon-bedrock-serverless-prompt-chaining/blob/main/functions/most_popular_repo_langchain/index.py#L79
* https://github.com/aws-samples/amazon-bedrock-serverless-prompt-chaining/blob/main/functions/most_popular_repo_langchain/index.py#L132

Note that Bedrock Agents does not yet support Claude 3, so that demo will not be updated.

**Comment by snowolf** [comment]
Thank you Clare.

Yes, I have noticed that, I am not familiar with CDK, so I manually changed model id in StepFunction. 

Most demo works well, however, I found in Trip plan demo, it doesn't use message API still "Human, Assistant", just for your heads up.

For Bedrock Agents, I noticed it as well, so I will stay tuned. However, for Langchain demo, I tried to manually modify related two Lambda code (lookup, summary), just change model id and "max_token_sample" to "max_token", but not worked, I will debug it later.

**Comment by clareliguori** [comment]
Where in the trip planner demo are you seeing it use Human/Assistant?  I thought I found all the places in [this commit](https://github.com/aws-samples/amazon-bedrock-serverless-prompt-chaining/commit/89202a9e60bafae82a3e96021122886e3d85e782#diff-12cbc57a0752021651e446dcaa338a2b080c9ec01675c40245ca0e44f7f8d8a2), but maybe I missed something
